### ISSUE TITLE
run-md.sh script does not kill services on build error

### ISSUE THREAD

**Issue by aanchal4** [interledger-rs/interledger-rs#520] opened 2019-11-19 19:28 UTC
If there is a build error while running one of the run-md.sh scripts in examples and the example does not run completely, then the services are not killed/stopped. When the example is re-run, the script still does not kill the services and gets stuck. @dora-gt

**Comment by dora-gt** [comment] 2019-11-22 08:40
Hmmm I'm not sure if this happens because all of our examples have the process that stops existing nodes, settlement engines and redis instances. Anyway, I'll look into.

**Comment by dora-gt** [comment] 2019-11-22 08:51
I just confirmed that even if there is compile errors, `run-md.sh` tries to stop existing processes.
Could you describe more about the situation? @aanchal4

**Comment by aanchal4** [comment] 2019-11-22 18:31
Here is what happens. 
1) Run `../../scripts/run-md.sh README.md`
2) Stop the script before it executes completely (services not killed)
3) Immediately re-run `../../scripts/run-md.sh README.md`
  - Displays: `"Stopping Interledger nodes..." `and is stuck forever.
4) Check running processes on the system.
 - Shows running redis-server and ilp-node instances.

**Comment by dora-gt** [comment] 2019-11-25 06:43
I tried sometimes but I could not reproduce...

**Comment by gakonst** [comment] 2019-11-28 13:59
Cannot reproduce either. Followed exact same steps. I Ctrl+C at the `Do you want to kill the services` prompt, so that the services remain alive. After that, when I rerun the script, it'll kill the services anyway, and things will proceed as normal.

**Comment by gakonst** [comment] 2019-12-13 00:06
Closing this, @aanchal4 if you can reproduce this from current master, please reopen

**Closed by gakonst** 2019-12-13 00:06 UTC
Labels: bug, docs
