### ISSUE TITLE
Unable to settle a payment between connectors

### ISSUE THREAD

**Issue by Tapanito** [interledger-rs/interledger-rs#581] opened 2019-12-23 09:56 UTC
Short summary: 

I've configured a few connectors using the following guide: https://github.com/interledger-rs/interledger-rs/tree/master/examples/xrp-settlement

However, I came across a strange behaviour. When I make a payment of 100 from Alice to Bob, I can see that the payment is settled on the ledger, but this is not reflected in the balances of the accounts. Alice's balance on node Alice, drops to -100, and Alice's balance on node Bob increases by a 100, however Bob's balance on node Bob stays at 0.
 I've investigated a bit further, I found the following error in the XRP Settlement Engine logs: `Error: Connector failed to process settlement: amountToCredit=0.0001 account=6dcc938f-0580-4257-8a49-a07a7d5fb9ce`. This is printed by the settlement engine, whenever the connector returns a response object other than the Quantity object defined in the RFC here: https://interledger.org/rfcs/0038-settlement-engines/ .

In my case, the connector returns a string `RECEIVED` I dug through the settlement code a bit, but I couldn't determine the cause of this, also the connector did not log any errors.

Commit hash or branch: I've built the latest master branch: `748591691bf787bee8aafd380ac3d5c5872d82e5`

I'm unable to determine whether  this is an issue with my configuration, or if there's some bug in the system. Any help would be greatly appreciated.

**Comment by gakonst** [comment] 2019-12-23 12:32
I recently changed the connector to always trust the engine for the received amount, moving all the leftover handling on the engine side. 

As per the RFC, the connector does not need to respond with anything meaningful to the engine
![image](https://user-images.githubusercontent.com/17802178/71358211-ea9e9080-2590-11ea-9a75-52c45e4ccc47.png)

@kincaidoneil is this just the engine giving a false-positive because it expected a quantity-response from the connector?

**Comment by Tapanito** [comment] 2019-12-23 14:05
Thank you for shedding some light on the matter @gakonst  . It explains the origins on the error, I don't understand, why when I make  a payment from Alice to Bob, Bob's account on node Bob does not get incremented? I.e. after I make a payment from Alice to Bob, Alice's account on node Alice is set to -100, Alice's account on node Bob is set to 100 (from what I understand this indicates the amount Alice owes Bob), however Bob's account  on node Bob is always zero.

**Comment by kincaidoneil** [comment] 2019-12-23 17:57
Nice catch, @gakonst. I'll fix that issue 👍 (I'm not sure that explains the balance inconsistencies though?)

**Comment by gakonst** [comment] 2019-12-26 10:34
@Tapanito I've tried reproducing manually and I am unable to. Can confirm that the XRP engine logs the error you mentioned, but we have already discussed that.

Could you please provide a detailed execution log of all the commands you execute to setup the accounts and make payments?

**Comment by Tapanito** [comment] 2019-12-30 19:47
@gakonst sorry for the delay. I'm running connectors on two VMs, with hostnames alice and bob (this will be important in the configs bellow). There is an XRP settlement engine running on each machine with the following env variables:
```
CONNECTOR_URL=http://127.0.0.1:7771
REDIS_URI=redis://127.0.0.1:6001
DEBUG=settlement*
```

Each connector is configured with the following config file:

```
secret_seed: 8852500887504328225458511465394229327394647958135038836332350604
admin_auth_token: $(hostname)
ilp_address: g.$(hostname)
database_url: redis://127.0.0.1:6000/
http_bind_address: 0.0.0.0:7770
settlement_api_bind_address: 127.0.0.1 :7771
prometheus:
  bind_address: 0.0.0.0:9654
  histogram_window: 300000
  histogram_granularity: 1000
```

For each VM I create the main account as follows:

```
 ilp-cli accounts create $(hostname) \
    --ilp-address g.$(hostname) \
    --asset-code XRP \
    --asset-scale 6 \
    --max-packet-amount 100 \
    --ilp-over-http-incoming-token $(hostname)\
    --settle-to 0 \
    --auth  $(hostname)
```

I link the accounts the following way, on Alice's node I create an account for Bob:

```
 ilp-cli accounts create bob \
      --auth $(hostname) \
      --ilp-address g.bob \
      --asset-code XRP \
      --asset-scale 6 \
      --max-packet-amount 100 \
      --settlement-engine-url http://localhost:3000 \
      --ilp-over-http-incoming-token bob \
      --ilp-over-http-outgoing-token alice \
      --ilp-over-http-url http://BOB_IP:7770/accounts/alice/ilp \
      --settle-threshold 500 \
      --min-balance -1000 \
      --settle-to 0 \
      --routing-relation Peer 
```

and do the same thing for Alice:

```
 ilp-cli accounts create alice \
      --auth $(hostname) \
      --ilp-address g.alice \
      --asset-code XRP \
      --asset-scale 6 \
      --max-packet-amount 100 \
      --settlement-engine-url http://localhost:3000 \
      --ilp-over-http-incoming-token alice \
      --ilp-over-http-outgoing-token bob \
      --ilp-over-http-url http://ALICE_IP:7770/accounts/bob/ilp \
      --settle-threshold 500 \
      --min-balance -1000 \
      --settle-to 0 \
      --routing-relation Peer 
```

Finally, I send a payment from Alice to Bob as follows:

```
ilp-cli pay alice \
    --auth $(hostname) \
    --amount 500 \
    --to http://BOB_IP:7770/accounts/bob/spsp
```

The funds get deduced from Alice's account on Alice's node, and get transferred to Alice's account on Bob's node.However, never reach Bob's account. When I check the test net, the xrp payment does get settled successfully.

**Comment by gakonst** [comment] 2020-01-20 10:18
@Tapanito 

Update: I've debugged this, the problem is that the engine decides that the amount `5e-4` is less than the acceptable granularity and holds it in the leftovers:

```
settlement-core Connector credited incoming settlement: leftover=0.0005 credited=0 amountToCredit=0.0005 account=763987ba-9748-4a51-becb-4177066d99ee settlementId=99607D752119D34C6AF3AF79C95DB70C95C7AC32EF60D87A46C34F4A379DF787 +0ms
```

Here's a script which reproduces this. @kincaidoneil this is on your side I believe, we had said that the engine will not need to track leftovers when it needs to notify the connector

**Comment by gakonst** [comment] 2020-01-27 06:25
@kincaidoneil were you able to look at this?

**Comment by gakonst** [comment] 2020-01-27 14:13
Closing @kincaidoneil please open a separate issue on settlement-core/ilp-settlement-xrp

**Closed by gakonst** 2020-01-27 14:13 UTC
Labels: bug, v1.0
