### ISSUE TITLE
The settlement of `eth-xrp-three-nodes` example **sometimes** fails

### ISSUE THREAD

**Issue by dora-gt** [interledger-rs/interledger-rs#439] opened 2019-10-21 08:55 UTC
The settlement of `eth-xrp-three-nodes` example **sometimes** fails. The logs are attached.

Potential causes are (though I'm not so sure):

`interledger-rs-node_b.log`
```
[ERROR interledger_store_redis::store] Error getting account from HTTP auth: An error was signalled by the server: Error running script (call to f_4f309de3c6e874e5de6f59384504d1a2d3f0c564): @user_script:5: user_script:5: attempt to concatenate local 'id' (a boolean value) 
```

`interledger-rs-node_b.log`
```
[ERROR interledger_settlement::api] Error sending message to peer settlement engine. Packet rejected with code: F00, message: Settlement engine rejected request with error code: 404 Not Found
```

- Failure case
    - [eth-xrp-three-nodes.zip](https://github.com/interledger-rs/interledger-rs/files/3749820/eth-xrp-three-nodes.zip)
- Success case
    - [eth-xrp-three-nodes.zip](https://github.com/interledger-rs/interledger-rs/files/3749888/eth-xrp-three-nodes.zip)

**Comment by bstrie** [comment] 2019-10-21 21:09
The first error is an error from within a Lua script, likely at the following line: https://github.com/interledger-rs/interledger-rs/blob/0bd9ce3e9f4332016bd93e96a855b23d04aafdd8/crates/interledger-store-redis/src/store.rs#L101 . The `..` is the concatenation operator in Lua, which works with both strings and numbers but not booleans. So the question is why `id` ends up being a boolean in some cases. (I don't think it's a case of `id` being the value 0 or 1, because that's not really how Lua represents booleans.) The `id` variable is received from the `redis.call` function, whose documentation lists the circumstances under which it will return which Lua types:
>    Redis integer reply -> Lua number
>    Redis bulk reply -> Lua string
>    Redis multi bulk reply -> Lua table (may have other Redis data types nested)
>    Redis status reply -> Lua table with a single ok field containing the status
>    Redis error reply -> Lua table with a single err field containing the error
>    Redis Nil bulk reply and Nil multi bulk reply -> Lua false boolean type
So it looks like redis is returning `false` to indicate that `redis.call('HGET', 'usernames', ARGV[1])` didn't find anything, which is strange because this `redis.call` only happens when the following returns true: `redis.call('HEXISTS', 'usernames', username)`.

So it could be a race condition where for some reason the username stops existing between the `HEXISTS` and `HGET` call, but I think that's supposed to be impossible because Lua scripts execute atomically within Redis (and if they don't, we have bigger problems!). It could also be something strange where the `HEXISTS` checks for `username` but the `HGET` uses `ARGV[1]`, but that would be very strange because the prior line is `local username = ARGV[1]`.

Pinging @emschwartz as the person most familiar with the Lua scripts.

**Comment by emschwartz** [comment] 2019-10-22 13:55
Lua scripts definitely execute atomically in Redis (see https://redis.io/commands/eval#atomicity-of-scripts).

I've been confused about this for a while because I would think that the `HEXISTS` call would be enough to check if the username is there. I don't think the problem is that it goes away, it seems more likely that it isn't there in the first place but for some reason that existence check returns true anyway.

If you can recreate this state, it may be worth checking what is stored in the usernames hash and whether it's possible that the value being stored there is incorrect (like if the value there was `false` somehow).

**Comment by bstrie** [comment] 2019-10-22 17:17
@dora-gt Let me know if you can reproduce the issue here now that https://github.com/interledger-rs/interledger-rs/pull/448 is merged.

**Comment by bstrie** [comment] 2019-10-22 17:18
(Note that #448 would only address the first error message, so let me know if you see that one specifically.)

**Comment by gakonst** [comment] 2019-11-28 14:08
@dora-gt can this be closed now? We haven't had any flakiness since the refactor of the engines and #448 I believe.

**Comment by gakonst** [comment] 2019-12-14 19:43
Closing, please re-open if you reproduce this from master

**Closed by gakonst** 2019-12-14 19:43 UTC
Labels: bug
